### ISSUE TITLE
See no difference on Just Watch. Amazon Prime Video is extremely slow

### ISSUE THREAD

**Issue by joelphilippage** [franciscolourenco/smoothkeyscroll#23]
I was trying to set up a desktop pc for streaming from different services and purchased this extension. I have both pro features toggled on.

I see no difference with this site:
https://www.justwatch.com/
Which is the main one I purchased it for because scrolling with the keyboard is so fast and that is the only way to navigate with my controller

Amazon prime video seems to only scroll a few pixels at a time when holding down the arrow key and hover effects while scrolling are still happening which is what I purchased the extension for.

Could you let me know if there is a fix? If not, could I get a refund?
Thanks!
-Joel

**Comment by franciscolourenco** [comment]
Hi @joelphilippage they are bugs which I will try to fix as soon as possible. 
In the meanwhile I've issued a refund.

Thank you for the report.
